package eco.humanos.android.core.model.task

import kotlinx.serialization.Serializable

/**
 * How an entity came into existence in the system.
 *
 * - [MANUAL] — explicitly created by the user.
 * - [IMPORTED] — pulled from an external system (QueBot, calendar, etc.).
 * - [INFERRED] — generated by AI from observed patterns or captures.
 * - [SEEDED] — pre-populated during onboarding or demo setup.
 */
@Serializable
enum class EntityOrigin {
    MANUAL,
    IMPORTED,
    INFERRED,
    SEEDED,
}
