package eco.humanos.android.data.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * [CredentialManager]-backed implementation of [GoogleCredentialManager].
 *
 * The Credential Manager UI must be anchored to an `Activity` context, so the
 * caller (the UI layer) passes its own context into [getGoogleIdToken] while
 * Hilt provides the application context used to build the manager and to
 * resolve resources.
 */
@Singleton
class GoogleCredentialManagerImpl @Inject constructor(
    @ApplicationContext private val context: Context,
) : GoogleCredentialManager {

    private val credentialManager: CredentialManager by lazy { CredentialManager.create(context) }

    override suspend fun getGoogleIdToken(activityContext: Context): Result<String> = runCatching {
        val serverClientId = resolveWebClientId()

        val googleIdOption = GetGoogleIdOption.Builder()
            .setServerClientId(serverClientId)
            // false → also offer accounts that have not previously authorized
            // this app, so first-time sign-in works.
            .setFilterByAuthorizedAccounts(false)
            .setAutoSelectEnabled(false)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        val response = credentialManager.getCredential(activityContext, request)
        val credential = response.credential

        if (credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
            throw IllegalStateException(
                "Unexpected credential type from Credential Manager: ${credential.type}",
            )
        }

        try {
            GoogleIdTokenCredential.createFrom(credential.data).idToken
        } catch (e: GoogleIdTokenParsingException) {
            throw IllegalStateException("Failed to parse Google ID token.", e)
        }
    }.recoverCatching { throwable ->
        // Surface a cleaner error for the common cancel / no-credential case,
        // but preserve the original cause.
        when (throwable) {
            is GetCredentialException ->
                throw IllegalStateException(
                    "Google Sign-In was cancelled or no credential was available.",
                    throwable,
                )
            else -> throw throwable
        }
    }

    /**
     * Resolves the web OAuth client ID generated by the google-services plugin
     * as `R.string.default_web_client_id`.
     *
     * This module is an Android library with its own package, so it cannot
     * import the application's `R`. The string resource is generated into the
     * APPLICATION package (eco.humanos.android) at app build time, so we look it
     * up by name at runtime against the running app's resources. Do NOT hardcode
     * the client ID — it lives only in google-services.json, which is gitignored.
     */
    private fun resolveWebClientId(): String {
        val resId = context.resources.getIdentifier(
            "default_web_client_id",
            "string",
            context.packageName,
        )
        check(resId != 0) {
            "default_web_client_id not found. Ensure google-services.json is present " +
                "and the google-services plugin is applied to the app module."
        }
        return context.getString(resId)
    }
}
